[greeter]
background = /usr/share/backgrounds/okayos/wallpaper.png
theme-name = Windows-10
icon-theme-name = Windows-10
font-name = Liberation Sans 10
xft-antialias = true
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %H:%M
